"""init

Revision ID: a2735e8c9cc3
Revises: 
Create Date: 2019-09-30 09:03:33.138489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2735e8c9cc3'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('session_path', sa.Text(), nullable=True),
    sa.Column('session_browser', sa.Text(), nullable=True),
    sa.Column('session_timestamp', sa.Float(), nullable=True),
    sa.Column('session_pdtb_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_session'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session')
    op.drop_index('my_index', table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
