"""No unique fields

Revision ID: 5bf85cd52e52
Revises: a2735e8c9cc3
Create Date: 2019-09-30 09:06:18.694232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf85cd52e52'
down_revision = 'a2735e8c9cc3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
